kind: Secret
apiVersion: v1
metadata:
  name: git-basic-auth-secret
type: Opaque
stringData:
  .gitconfig: |
    [credential "https://github.com"]
      helper = store
  .git-credentials: |
    https://yuhaozh-jxbot-1:xxxxx@github.com
